// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5coIKiqrP60jrF0DzhSf6cAIxg_xCtTE',
    appId: '1:36299042266:android:d01d9e3214272c461d24e3',
    messagingSenderId: '36299042266',
    projectId: 'dev--sync',
    storageBucket: 'dev--sync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBluxh9QW0tbVERb3JUJrhOhpaZV-ovvGg',
    appId: '1:36299042266:ios:1fc7c30a88341d971d24e3',
    messagingSenderId: '36299042266',
    projectId: 'dev--sync',
    storageBucket: 'dev--sync.firebasestorage.app',
    androidClientId: '36299042266-djb0rhpfou9tbtustdhqorjddsdcijt9.apps.googleusercontent.com',
    iosClientId: '36299042266-oobhq6dbuesd77epdjammcakimkhniht.apps.googleusercontent.com',
    iosBundleId: 'com.devsync.devMatchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3x6O50BtK4m2U6zuZgZWR_JClmQfpF64',
    appId: '1:36299042266:web:d045c59610f39ac31d24e3',
    messagingSenderId: '36299042266',
    projectId: 'dev--sync',
    authDomain: 'dev--sync.firebaseapp.com',
    storageBucket: 'dev--sync.firebasestorage.app',
    measurementId: 'G-5R93FKFM1K',
  );
}